#!/bin/bash

echo "=== ZSH LLM Debugger Streaming Demo ==="
echo ""
echo "1. Loading the plugin..."
source zsh-llm-debugger.plugin.zsh

echo ""
echo "2. Testing streaming command generation..."
echo ""
echo "When you type:"
echo "    generate_command \"find all files larger than 1MB\""
echo ""
echo "You will see:"
echo "    💭 Thinking..."
echo "    [AI reasoning process streams here in real-time]"
echo "    ▶ find . -size +1M -type f"
echo ""

echo "3. Testing the ?? interactive mode..."
echo ""
echo "When you type:"
echo "    ?? compress a directory with tar"
echo ""
echo "You will see in the command line buffer:"
echo "    💭 Thinking..."
echo "    [thinking content streams]"
echo "    tar -czf archive.tar.gz directory/"
echo ""
echo "The command appears as a gray suggestion that you can:"
echo "    - Accept with Right Arrow, End key, or Tab"
echo "    - Cancel with Escape or Ctrl+C"
echo ""

echo "=== Streaming Features ==="
echo "✅ Real-time AI thinking display"
echo "✅ Special <think> tag handling"
echo "✅ Character-by-character streaming"
echo "✅ Visual thinking vs command differentiation"
echo "✅ Clean command extraction"
echo "✅ Interactive suggestion interface"
echo ""

echo "Try it yourself: generate_command \"your request here\""
